# Generated by Django 2.2.19 on 2021-06-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0038_ticket_time_before_first_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericincident',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archivé'),
        ),
    ]
