# Generated by Django 2.2.19 on 2021-07-12 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sphinx', '0096_auto_20210528_1557'),
        ('helpdesk', '0039_genericincident_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleUserMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='mail')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sphinx.Customer', verbose_name='Client')),
            ],
            options={
                'verbose_name': "Email d'un simple utilisateur",
                'verbose_name_plural': 'Emails de simples utilisateurs',
            },
        ),
    ]
